### ISSUE TITLE
Set up continuous integration 

### ISSUE THREAD

**Issue by mrchrisadams** [Greening-Digital/constellate#1]
When we make changes we need to run tests, using github actions. These would include:

### TODOS

- [x] run the tests on each push
- [x] get a fixed set of dependencies to enable reproducible builds

- [x] have at least one passing test using jest vue-utils (many of the tests will be out of date 😱 - so it's not worth trying to get them _all_ running til we know if they are doing anything useful)

**Comment by mrchrisadams** [comment]
@rmparr, I think I can add a skeleton for setting up GH actions, to run something like `npm run test` on each push.

I think jest does provide coverage output, that i think stuff like [coveralls][1] can track.

[1]: https://coveralls.io/

https://jestjs.io/docs/en/cli.html#--coverageboolean

**Comment by mrchrisadams** [comment]
ok @rmparr to summarise our chat, I'll set up the initial GH action to run a test command, and make a PR including it, if you start with the making the test command detect the tests in the repo again.

**Comment by mrchrisadams** [comment]
Okay, there's a handy action for tracking coverage: 

https://github.com/marketplace/actions/coveralls-github-action

**Comment by rmparr** [comment]
The coverage and output from Jest is not bad. Luckily, we can add the flag to the action if we want, instead of making changes to the rest of the repo.

Do you want to authorize coveralls for Greening-Digital?

**Comment by mrchrisadams** [comment]
Yeah man! I mean, it can only go _up_ from here, right?

**Comment by mrchrisadams** [comment]
hey @rmparr , can you let me know if this action here was the one that still needed the token in a git repo for us to get stats still? A quick look over makes me think because the it relies on a github token specific to this repo, only our changes would trigger a build to update the stats:

https://github.com/coverallsapp/github-action/ 

If not, and if it's a pain to use, we could break this into a separate issue to have as a 'good first issue' so we can at least close this one.

WDYT?

**Comment by rmparr** [comment]
This action requires a separate token (`repo_token`), available to the GitHub action, to push the results to Coveralls.

Coveralls provides the token; the issue thus far has been making that token available to the action, or having the action actually respect the environment variable. So far, setting GitHub Secrets is not having the expected results.

We can work around this by generating the code coverage and shipping to Coveralls locally, which is my recommendation currently.

**Comment by mrchrisadams** [comment]
Cool, that works at my end - we can still see the coverage, and this sounds like the thing that we can resolve separately from the rest of setting up the pipeline.

**Comment by mrchrisadams** [comment]
OK, I've moved the coveralls coverage issue into a separate issue. It's useful, but not a show stopper, and the kind of thing that asking around to see who has set up GH actions and coveralls together will likely solve than us bashing our heads against a brick wall here.
