### ISSUE TITLE
Develop importer from plain old CSV files instead of airtable

### ISSUE THREAD

**Issue by mrchrisadams** [Greening-Digital/constellate#15]
In #8 , we cover some steps we might make to change the schema in airtable to make it more generic and easier to use without being coupled to the service.

Ideally we'd be able to import the same kind of data in a CSV file, and have it create the same data structure and users in firebase, as a first step to being able to create this structure that isn't tied to Firebase.

So the goal of this issue is to take a CSV file with the same schema as we have on airtable, and be able to import to create a new constellation, making the user and profile creation API calls.

# Todo (incomplete, feel free to adjust)

- [x] generate csv file based on updated schema
- [x] add some basic checking of type for columns
- [x] write importer to make the same API calls against firebase database and user authentication systems
