### ISSUE TITLE
Replace main listing views with regular django templates

### ISSUE THREAD

**Issue by mrchrisadams** [Greening-Digital/constellate#187]
This covers having the same email based sign up flow as before. Updating sign-in via slack is out of scope. 

The minimum usable version of this would be to display matching profiles again for a given combination of search terms and active tags, like we had with the original Vue JS version.

### Todo 

- [x] Filter by tags and bio text
- [x] new profile page template (not redesigned yet)
- [x] update profile list in an HTMX fashion based on query

**Comment by mrchrisadams** [comment]
I've had some success with using Django tailwind, django reload and daisy UI.

They offer a nice experience to develop with, and doing so lets me use tooling I'm familiar with and productive with, and have set up before.

**Comment by mrchrisadams** [comment]
OK, we have this, but not the filtering. Django filter is likely the fastest way to add filtering.

Maybe with django HTMX for filtering the sidebar and main profile view

**Comment by mrchrisadams** [comment]
OK, django filter worked nicely! Using `conjoined=True`, you can make django filter to AND queries nicely as well.

Django HTMX would be nice, but it's a thing we could add later, once we have the main profile listed

**Comment by mrchrisadams** [comment]
This was implemented, and in the main branch now.
