### ISSUE TITLE
Front end Tidyup checklist

### ISSUE THREAD

**Issue by mrchrisadams** [Greening-Digital/constellate#40]
We've uncovered a fair few things to tidy up as we work on various issues, that might not warrant being full issues here.

This issue is a place for adding todos to flesh out into proper tasks:

- [x] remove firebase server application
- [x] replace firebase calls with axios calls
- [x] remove unnecessary firebase actions
- [x] remove firebase script
- [x] remove firebase dependencies
- [ ] remove firebase configuration files
