### ISSUE TITLE
Set up environment to deploy to, visible to end users

### ISSUE THREAD

**Issue by mrchrisadams** [Greening-Digital/constellate#9]
With CI working, we ideally want a way to deploy changes as part of the pipeline.

### Todo

- [x] decide the deployment strategy
- [x] decide how many environments to have (i.e. dev, prod, etc)
- [x] hook up the deployment gubbins so pushing, or merging a given branch triggers the deploy to appropriate place. [See the handy firebase action ][gh2fb]

[gh2fb]: https://github.com/marketplace/actions/github-action-for-firebase

**Comment by mrchrisadams** [comment]
After a conversation, setting up the automated pipeline, using the current tooling to push new to deploys to the `constellate-dev` environment using dummy data seems the best idea.

This will allow someone to see the end to end pipeline of services required, without anyone needing to sign up or share their data.

**Comment by mrchrisadams** [comment]
There is now a `demo` branch, that when pushed to, will trigger deploy to the following url, with the most recent build of the app:

https://constellate-demo.firebaseapp.com/

The data, and files on this will be cleared, and imported every few hour, with at least one set admin role, and one set end user role, with default credentials to log in with.

This lets us demonstrate functionality, and hopefully have a meaningful conversation about features, and allows any other organisation to fork the code and integrate it into a pipeline like one offered by Heroku or similar.
